name: Run Agave
on: 
  push:
    branches:
      - main
jobs:
  agave:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: build site
        run: |
          # do some operation that changes a file in the git repo
          npm i
          npm run build

      - name: git config
        run: |
          git config user.name "GitHub Bot"
          git config user.email "jottenlips+ghbot@gmail.com"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add --all
          git commit -m "deploy site"
          git push origin main